### ISSUE TITLE
It's difficult to determine the point # from the ERC721 metadata

### ISSUE THREAD

**Issue by msutherl** [urbit/azimuth#10]
I was recently interested to look up information about a point I found on OpenSea using the contract interface directly: https://etherscan.io/address/azimuth.eth#readContract and discovered that it would be nearly impossible for someone with less context than myself to determine the point number from the metadata.

Possibilities:

1. This may not be an important concern for anybody in practice
2. An easily accessible @p → point number utility may suffice
3. It could make sense to add this to the metadata, but might be overkill

**Comment by jtobin** [comment]
This one can probably be closed with a pointer to the following ways to retrieve the point number from a `@p`:

## :dojo

```
~nidsut-tomdun:dojo> `@`~nidsut-tomdun
15.663.360
```

## [urbit-ob](https://www.npmjs.com/package/urbit-ob)

```
> const ob = require('urbit-ob')
> ob.patp2dec('~nidsut-tomdun')
'15663360'
```

## [urbit-hob](https://hackage.haskell.org/package/urbit-hob)

```
> import qualified Urbit.Ob as Ob
> Ob.fromPatp <$> Ob.parsePatp "~nidsut-tomdun"
Right 15663360
```
