### ISSUE TITLE
Broken link on azimuth.network

### ISSUE THREAD

**Issue by ronreg-ribdev** [urbit/azimuth#23]
The link to "Etherscan" on the azimuth.network page is broken:

```
<a href="https://https://etherscan.io/address/azimuth.eth" target="_blank">
            <h5 class="inline underline">Etherscan ↗</h5>
          </a>
```

**Comment by Fang-** [comment]
We had fixed this some time ago, but never pushed it to production. Thanks for the heads up, fixed now!
