### ISSUE TITLE
Tests & deployment broken

### ISSUE THREAD

**Issue by jtobin** [urbit/azimuth#28]
This is what we get for not running CI.. :smile:  (because #13)

I'm not sure when this happened exactly, but the test suite doesn't pass.  Like, more than is described in #13. There are some problems with `migrations/2_deploy_contracts.js` that will prevent it from running at all -- web3 is used, but never imported nor a web3 object created, and the web3 version pinned in package.json has a different API than the code used in there anyway (e.g. it seems `web3.fromAscii` should be used in place of `web3.utils.fromAscii`).

But after fixing that up or checking out c950c6ae681b7fdaa5cb5e7e12e8d387d3751799, the last commit before those changes were made, the test suite doesn't pass.  Even checking out v1.2.1, the tests don't pass.  I haven't checked back any further yet.

/cc @liam-fitzgerald @Fang-

**Comment by jtobin** [comment]
(I can confirm that they do run as expected at v1.1.0.)

**Comment by Fang-** [comment]
Well, I can repro this at least, getting:

```
/Users/fang/repos/urbit/constitution/migrations/2_deploy_contracts.js:15
const condit2 = web3.utils.fromAscii("1234");
                           ^

TypeError: Cannot read property 'fromAscii' of undefined
    at /Users/fang/repos/urbit/constitution/migrations/2_deploy_contracts.js:15:28
```

Tests run if you replace `web3.utils.` with `web3.` in that file, so maybe we just need to either upgrade the pinned web3 version, or change that file?

Some linear star release tests still fail, because web3 handles overloaded functions rather poorly. Maybe that'd be fixed in a new version...

**Comment by jtobin** [comment]
> Tests run if you replace web3.utils. with web3. in that file, so maybe we just need to either upgrade the pinned web3 version, or change that file?

Aha.  So I was getting much worse failures yesterday.  Apparently we don't have a web3 dependency pinned in package.json at all, so I must have implicitly been pulling in a different web3 version when trying to test / fix the issue.

The lockfile on master includes web3 at at least v1.2.1, v1.2.2, and v1.2.6 as it pulls it in for various other dependencies.  If I just add `var web3 = require('web3');` at the top of `migrations/2_deploy_contracts.js` today, I don't even have to patch `web3.utils.fromAscii` to `web3.fromAscii`.  Just importing the library is good enough to make the tests run (although many don't pass).

Adding the latest version of web3 (v1.2.7), to devDependencies seems to make most of the tests pass, although I do still see a substantial number of failures (not in the linear star release contract, either).

It's safe to say that this is all a bit of a mess, in any case, and heavily depends on the state of one's node_modules directory.

**Comment by jtobin** [comment]
As an aside, azimuth-js is specifying a much older web3 peer dependency of v1.0.0-beta.54, so it's possible those should be unified as well.

**Comment by johnmendonca** [comment]
I am getting the same fromAscii error during `npx truffle deploy`.  It looks like just importing web3 would be the fix as mentioned above, but I wasn't sure if truffle was supposed to provide an instance implicitly.  I'm not seeing web3 in package.json as a peer dependency or anything else, here are the versions I ended up with:

```
$ npm list web3
azimuth-solidity@1.2.1 /home/john/code/azimuth
└─┬ solidity-coverage@0.7.7
  ├─┬ @truffle/provider@0.1.19
  │ ├─┬ @truffle/interface-adapter@0.3.3
  │ │ └── web3@1.2.2
  │ └── web3@1.2.1
  └── web3@1.2.6
```

**Comment by johnmendonca** [comment]
I've got the deploy script working by adding the following to the top of `2_deploy_contracts.js`:

```
var Web3 = require('web3');
var web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:7545'));
```

I am running a Ganache instance on port 7545, and updated the port number in `truffle.js`

**Comment by cxk280** [comment]
Regarding the post immediately above: you probably want `localhost:8545`, not `localhost:7545`. The former is what is currently configured in `truffle.js` and is the [default configuration](https://www.trufflesuite.com/docs/truffle/reference/configuration).
